[build]
  command="cd functions && npm i && cd.."
  publish="public"
  functions="functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
    from = "/"
    to = "/.netlify/functions/run"
    status = 200